import {
  CircuitElement,
  CircuitWire,
  TransientSettings,
} from '../types';

export interface SampleCircuit {
  id: string;
  name: string;
  category: string;
  description: string;
  pageRef?: string;
  elements: CircuitElement[];
  wires: CircuitWire[];
  transient: TransientSettings;
}

export const SAMPLE_CIRCUITS: SampleCircuit[] = [
  // 0. Эталонная схема для проверки редактора и расчёта.
  // Синхронный понижающий преобразователь: U1 (100 В), U2 (100 кГц / 50%), VCK1, NOT1, VCK2, R1 (10 мОм), L1 (100 мкГн), C2 (100 мкФ), R2 (10 мОм), R3 (10 Ом)
  {
    id: 'synchronous-buck',
    name: 'Синхронный понижающий преобразователь',
    category: 'Импульсные преобразователи',
    description: 'Синхронный импульсный стабилизатор с полумостовыми ключами VCK1/VCK2, логическим инвертором NOT1, LC-фильтром (100 мкГн, 100 мкФ) и активной нагрузкой 10 Ом.',
    pageRef: 'Untitled.scm',
    elements: [
      {
        id: 'u1',
        type: 'V_DC',
        name: 'U1',
        x: 80,
        y: 340,
        rotation: 0,
        value: 100,
        valueStr: '100 В',
        unit: 'В',
      },
      {
        id: 'u2',
        type: 'V_PULSE',
        name: 'U2',
        x: 170,
        y: 360,
        rotation: 0,
        value: 100000,
        valueStr: '100 кГц / 50 %',
        secondaryValue: 100000,
        secondaryStr: '100 кГц',
        unit: 'Гц',
      },
      {
        id: 'vck1',
        type: 'SWITCH',
        name: 'VCK1',
        x: 260,
        y: 240,
        rotation: 0,
        value: 100000,
        valueStr: '',
        unit: '',
      },
      {
        id: 'not1',
        type: 'NOT',
        name: 'NOT1',
        x: 260,
        y: 340,
        rotation: 0,
        value: 0,
        valueStr: '',
        unit: '',
      },
      {
        id: 'vck2',
        type: 'SWITCH',
        name: 'VCK2',
        x: 320,
        y: 380,
        rotation: 270,
        value: 100000,
        valueStr: '',
        unit: '',
      },
      {
        id: 'r1',
        type: 'R',
        name: 'R1',
        x: 360,
        y: 240,
        rotation: 0,
        value: 0.01,
        valueStr: '10 мОм',
        unit: 'Ом',
      },
      {
        id: 'l1',
        type: 'L',
        name: 'L1',
        x: 440,
        y: 240,
        rotation: 0,
        value: 100e-6,
        valueStr: '100 мкГн',
        unit: 'Гн',
      },
      {
        id: 'c2',
        type: 'C',
        name: 'C2',
        x: 520,
        y: 300,
        rotation: 90,
        value: 100e-6,
        valueStr: '100 мкФ',
        unit: 'Ф',
      },
      {
        id: 'r2',
        type: 'R',
        name: 'R2',
        x: 520,
        y: 380,
        rotation: 90,
        value: 0.01,
        valueStr: '10 мОм',
        unit: 'Ом',
      },
      {
        id: 'r3',
        type: 'R',
        name: 'R3',
        x: 620,
        y: 340,
        rotation: 90,
        value: 10,
        valueStr: '10 Ом',
        unit: 'Ом',
      },
      {
        id: 'gnd',
        type: 'GND',
        name: 'GND1',
        x: 320,
        y: 440,
        rotation: 0,
        value: 0,
        valueStr: '',
        unit: '',
      },
    ],
    wires: [
      // Узел 5: U1(+) -> VCK1.1 (Коллектор)
      { id: 'w_u1_vck1', fromCompId: 'u1', fromPinId: '1', toCompId: 'vck1', toPinId: '1' },
      // Узел 6: U2(+) -> VCK1.gate и U2(+) -> NOT1.1
      { id: 'w_u2_vck1_g', fromCompId: 'u2', fromPinId: '1', toCompId: 'vck1', toPinId: 'gate' },
      { id: 'w_u2_not1', fromCompId: 'u2', fromPinId: '1', toCompId: 'not1', toPinId: '1' },
      // Узел 7: NOT1.2 -> VCK2.gate
      { id: 'w_not1_vck2_g', fromCompId: 'not1', fromPinId: '2', toCompId: 'vck2', toPinId: 'gate' },
      // Узел 4: VCK1.2 -> R1.1 и VCK1.2 -> VCK2.1
      { id: 'w_vck1_r1', fromCompId: 'vck1', fromPinId: '2', toCompId: 'r1', toPinId: '1' },
      { id: 'w_vck1_vck2', fromCompId: 'vck1', fromPinId: '2', toCompId: 'vck2', toPinId: '1' },
      // Узел 1: R1.2 -> L1.1
      { id: 'w_r1_l1', fromCompId: 'r1', fromPinId: '2', toCompId: 'l1', toPinId: '1' },
      // Узел 2: L1.2 -> C2.1 и L1.2 -> R3.1
      { id: 'w_l1_c2', fromCompId: 'l1', fromPinId: '2', toCompId: 'c2', toPinId: '1' },
      { id: 'w_l1_r3', fromCompId: 'l1', fromPinId: '2', toCompId: 'r3', toPinId: '1' },
      // Узел 3: C2.2 -> R2.1
      { id: 'w_c2_r2', fromCompId: 'c2', fromPinId: '2', toCompId: 'r2', toPinId: '1' },
      // Шина земли GND:
      { id: 'w_gnd_u1', fromCompId: 'gnd', fromPinId: '1', toCompId: 'u1', toPinId: '2' },
      { id: 'w_gnd_u2', fromCompId: 'gnd', fromPinId: '1', toCompId: 'u2', toPinId: '2' },
      { id: 'w_gnd_vck2', fromCompId: 'gnd', fromPinId: '1', toCompId: 'vck2', toPinId: '2' },
      { id: 'w_gnd_r2', fromCompId: 'gnd', fromPinId: '1', toCompId: 'r2', toPinId: '2' },
      { id: 'w_gnd_r3', fromCompId: 'gnd', fromPinId: '1', toCompId: 'r3', toPinId: '2' },
    ],
    transient: {
      tMax: 0.0003,
      tMaxStr: '300u',
      step: 0.0003 / 500,
      stepStr: 'tmax/500',
      eps: 0.001,
      signals: [
        {
          id: 'sig_u_out',
          plotIndex: 1,
          exprX: 't',
          exprY: 'U(2)',
          color: '#2563eb',
          enabled: true,
        },
        {
          id: 'sig_u_sw',
          plotIndex: 1,
          exprX: 't',
          exprY: 'U(4)',
          color: '#10b981',
          enabled: true,
        },
        {
          id: 'sig_i_l1',
          plotIndex: 2,
          exprX: 't',
          exprY: 'I(L1)',
          color: '#dc2626',
          enabled: true,
        },
        {
          id: 'sig_i_r3',
          plotIndex: 2,
          exprX: 't',
          exprY: 'I(R3)',
          color: '#f59e0b',
          enabled: true,
        },
      ],
    },
  },

  // 1. ФНЧ 1-го порядка (RC-фильтр).
  {
    id: 'rc-filter',
    name: 'ФНЧ 1-го порядка (RC-фильтр)',
    category: 'Линейные цепи',
    description: 'Классический RC-фильтр нижних частот. U1 = 1 В, R1 = 1 кОм, C1 = 1 мкФ.',
    pageRef: 'стр. 24–25',
    elements: [
      {
        id: 'u1',
        type: 'V_DC',
        name: 'U1',
        x: 100,
        y: 200,
        rotation: 0,
        value: 1,
        valueStr: '1 В',
        unit: 'В',
      },
      {
        id: 'port_in',
        type: 'PORT',
        name: 'PORT_IN',
        portName: 'IN',
        x: 100,
        y: 120,
        rotation: 0,
        value: 0,
        valueStr: '',
        unit: '',
      },
      {
        id: 'r1',
        type: 'R',
        name: 'R1',
        x: 240,
        y: 120,
        rotation: 0,
        value: 1000,
        valueStr: '1 кОм',
        unit: 'Ом',
      },
      {
        id: 'c1',
        type: 'C',
        name: 'C1',
        x: 360,
        y: 200,
        rotation: 90,
        value: 1e-6,
        valueStr: '1 мкФ',
        unit: 'Ф',
        initialCondition: 0,
      },
      {
        id: 'port_out',
        type: 'PORT',
        name: 'PORT_OUT',
        portName: 'OUT',
        x: 460,
        y: 120,
        rotation: 0,
        value: 0,
        valueStr: '',
        unit: '',
      },
      {
        id: 'gnd1',
        type: 'GND',
        name: 'GND1',
        x: 100,
        y: 280,
        rotation: 0,
        value: 0,
        valueStr: '',
        unit: '',
      },
      {
        id: 'gnd2',
        type: 'GND',
        name: 'GND2',
        x: 360,
        y: 280,
        rotation: 0,
        value: 0,
        valueStr: '',
        unit: '',
      },
      {
        id: 'txt1',
        type: 'TEXT',
        name: 'TXT1',
        x: 100,
        y: 50,
        rotation: 0,
        value: 0,
        valueStr: '',
        unit: '',
        textDirective: '.define tau = R1.R * C1.C; % Постоянная времени тау = 1 мс',
      },
    ],
    wires: [
      { id: 'w1', fromCompId: 'u1', fromPinId: '1', toCompId: 'port_in', toPinId: '1' },
      { id: 'w2', fromCompId: 'port_in', fromPinId: '1', toCompId: 'r1', toPinId: '1' },
      { id: 'w3', fromCompId: 'r1', fromPinId: '2', toCompId: 'c1', toPinId: '1' },
      { id: 'w4', fromCompId: 'c1', fromPinId: '1', toCompId: 'port_out', toPinId: '1' },
      { id: 'w5', fromCompId: 'u1', fromPinId: '2', toCompId: 'gnd1', toPinId: '1' },
      { id: 'w6', fromCompId: 'c1', fromPinId: '2', toCompId: 'gnd2', toPinId: '1' },
    ],
    transient: {
      tMax: 0.005,
      tMaxStr: '5m',
      step: 1e-5,
      stepStr: '10u',
      eps: 0.001,
      signals: [
        { id: 's1', plotIndex: 1, exprX: 't', exprY: 'U(IN)', color: '#2563eb', enabled: true },
        { id: 's2', plotIndex: 1, exprX: 't', exprY: 'U(OUT)', color: '#dc2626', enabled: true },
        { id: 's3', plotIndex: 2, exprX: 't', exprY: 'I(R1)', color: '#059669', enabled: true },
      ],
    },
  },

  // 2. ШИМ-преобразователь понижающий (Buck Converter).
  {
    id: 'buck-converter',
    name: 'ШИМ-преобразователь понижающий (Buck PWM)',
    category: 'Импульсные преобразователи',
    description: 'Импульсный DC-DC понижающий преобразователь с LC-фильтром и диодом рекуперации. U_in = 50 В, L = 0.5 мГн, C = 10 мкФ, R = 10 Ом.',
    pageRef: 'стр. 37–38',
    elements: [
      {
        id: 'u_dc',
        type: 'V_DC',
        name: 'U1',
        x: 80,
        y: 200,
        rotation: 0,
        value: 50,
        valueStr: '50 В',
        unit: 'В',
      },
      {
        id: 'sw1',
        type: 'SWITCH',
        name: 'MOS1',
        x: 200,
        y: 120,
        rotation: 0,
        value: 20000,
        valueStr: '20 кГц',
        unit: 'Гц',
      },
      {
        id: 'port_sw',
        type: 'PORT',
        name: 'PORT_SW',
        portName: 'SW',
        x: 270,
        y: 80,
        rotation: 0,
        value: 0,
        valueStr: '',
        unit: '',
      },
      {
        id: 'd1',
        type: 'DIODE',
        name: 'D1',
        x: 270,
        y: 200,
        rotation: 270,
        value: 0,
        valueStr: 'Диод',
        unit: '',
      },
      {
        id: 'l1',
        type: 'L',
        name: 'L1',
        x: 370,
        y: 120,
        rotation: 0,
        value: 0.5e-3,
        valueStr: '0.5 мГн',
        unit: 'Гн',
      },
      {
        id: 'c1',
        type: 'C',
        name: 'C1',
        x: 480,
        y: 200,
        rotation: 90,
        value: 10e-6,
        valueStr: '10 мкФ',
        unit: 'Ф',
      },
      {
        id: 'r_load',
        type: 'R',
        name: 'R2',
        x: 580,
        y: 200,
        rotation: 90,
        value: 10,
        valueStr: '10 Ом',
        unit: 'Ом',
      },
      {
        id: 'port_out',
        type: 'PORT',
        name: 'PORT_OUT',
        portName: 'OUT',
        x: 660,
        y: 120,
        rotation: 0,
        value: 0,
        valueStr: '',
        unit: '',
      },
      {
        id: 'gnd_main',
        type: 'GND',
        name: 'GND1',
        x: 80,
        y: 280,
        rotation: 0,
        value: 0,
        valueStr: '',
        unit: '',
      },
      {
        id: 'gnd_d',
        type: 'GND',
        name: 'GND2',
        x: 270,
        y: 280,
        rotation: 0,
        value: 0,
        valueStr: '',
        unit: '',
      },
      {
        id: 'gnd_c',
        type: 'GND',
        name: 'GND3',
        x: 480,
        y: 280,
        rotation: 0,
        value: 0,
        valueStr: '',
        unit: '',
      },
      {
        id: 'gnd_r',
        type: 'GND',
        name: 'GND4',
        x: 580,
        y: 280,
        rotation: 0,
        value: 0,
        valueStr: '',
        unit: '',
      },
    ],
    wires: [
      { id: 'w1', fromCompId: 'u_dc', fromPinId: '1', toCompId: 'sw1', toPinId: '1' },
      { id: 'w2', fromCompId: 'sw1', fromPinId: '2', toCompId: 'port_sw', toPinId: '1' },
      { id: 'w3', fromCompId: 'port_sw', fromPinId: '1', toCompId: 'l1', toPinId: '1' },
      { id: 'w4', fromCompId: 'port_sw', fromPinId: '1', toCompId: 'd1', toPinId: '2' }, // катод к узлу
      { id: 'w5', fromCompId: 'l1', fromPinId: '2', toCompId: 'c1', toPinId: '1' },
      { id: 'w6', fromCompId: 'c1', fromPinId: '1', toCompId: 'r_load', toPinId: '1' },
      { id: 'w7', fromCompId: 'r_load', fromPinId: '1', toCompId: 'port_out', toPinId: '1' },
      { id: 'w8', fromCompId: 'u_dc', fromPinId: '2', toCompId: 'gnd_main', toPinId: '1' },
      { id: 'w9', fromCompId: 'd1', fromPinId: '1', toCompId: 'gnd_d', toPinId: '1' },
      { id: 'w10', fromCompId: 'c1', fromPinId: '2', toCompId: 'gnd_c', toPinId: '1' },
      { id: 'w11', fromCompId: 'r_load', fromPinId: '2', toCompId: 'gnd_r', toPinId: '1' },
    ],
    transient: {
      tMax: 0.003,
      tMaxStr: '3m',
      step: 5e-6,
      stepStr: '5u',
      eps: 0.001,
      signals: [
        { id: 's1', plotIndex: 1, exprX: 't', exprY: 'U(OUT)', color: '#dc2626', enabled: true },
        { id: 's2', plotIndex: 1, exprX: 't', exprY: 'U(SW)', color: '#2563eb', enabled: true },
        { id: 's3', plotIndex: 2, exprX: 't', exprY: 'I(L1)', color: '#059669', enabled: true },
        { id: 's4', plotIndex: 2, exprX: 't', exprY: 'I(R2)', color: '#d97706', enabled: true },
      ],
    },
  },

  // 3. Инвертирующий усилитель на ОУ — стр. 4, 15, 22 мануала
  {
    id: 'opamp-inverting',
    name: 'Инвертирующий усилитель на ОУ',
    category: 'Аналоговая схемотехника',
    description: 'Усилитель на базе идеального операционного усилителя ОУ1 (K=1e6) с резистивной отрицательной обратной связью (стр. 4, 15, 22 руководства). Ку = -R2/R1 = -10.',
    pageRef: 'стр. 4, 15, 22',
    elements: [
      {
        id: 'u_ac',
        type: 'V_AC',
        name: 'U1',
        x: 80,
        y: 220,
        rotation: 0,
        value: 1,
        valueStr: '1 В',
        unit: 'В',
        secondaryValue: 1000,
        secondaryStr: '1 кГц',
      },
      {
        id: 'port_in',
        type: 'PORT',
        name: 'PORT_IN',
        portName: 'IN',
        x: 80,
        y: 140,
        rotation: 0,
        value: 0,
        valueStr: '',
        unit: '',
      },
      {
        id: 'r1',
        type: 'R',
        name: 'R1',
        x: 200,
        y: 140,
        rotation: 0,
        value: 1000,
        valueStr: '1 кОм',
        unit: 'Ом',
      },
      {
        id: 'op1',
        type: 'OPAMP',
        name: 'ОУ1',
        x: 360,
        y: 180,
        rotation: 0,
        value: 1e6,
        valueStr: '1M',
        unit: 'В/В',
      },
      {
        id: 'r2',
        type: 'R',
        name: 'R2',
        x: 360,
        y: 70,
        rotation: 0,
        value: 10000,
        valueStr: '10 кОм',
        unit: 'Ом',
      },
      {
        id: 'port_out',
        type: 'PORT',
        name: 'PORT_OUT',
        portName: 'OUT',
        x: 480,
        y: 180,
        rotation: 0,
        value: 0,
        valueStr: '',
        unit: '',
      },
      {
        id: 'gnd1',
        type: 'GND',
        name: 'GND1',
        x: 80,
        y: 300,
        rotation: 0,
        value: 0,
        valueStr: '',
        unit: '',
      },
      {
        id: 'gnd_op',
        type: 'GND',
        name: 'GND2',
        x: 310,
        y: 260,
        rotation: 0,
        value: 0,
        valueStr: '',
        unit: '',
      },
    ],
    wires: [
      { id: 'w1', fromCompId: 'u_ac', fromPinId: '1', toCompId: 'port_in', toPinId: '1' },
      { id: 'w2', fromCompId: 'port_in', fromPinId: '1', toCompId: 'r1', toPinId: '1' },
      { id: 'w3', fromCompId: 'r1', fromPinId: '2', toCompId: 'op1', toPinId: 'in_neg' },
      { id: 'w4', fromCompId: 'r1', fromPinId: '2', toCompId: 'r2', toPinId: '1' },
      { id: 'w5', fromCompId: 'r2', fromPinId: '2', toCompId: 'op1', toPinId: 'out' },
      { id: 'w6', fromCompId: 'op1', fromPinId: 'out', toCompId: 'port_out', toPinId: '1' },
      { id: 'w7', fromCompId: 'op1', fromPinId: 'in_pos', toCompId: 'gnd_op', toPinId: '1' },
      { id: 'w8', fromCompId: 'u_ac', fromPinId: '2', toCompId: 'gnd1', toPinId: '1' },
    ],
    transient: {
      tMax: 0.003,
      tMaxStr: '3m',
      step: 1e-5,
      stepStr: '10u',
      eps: 0.001,
      signals: [
        { id: 's1', plotIndex: 1, exprX: 't', exprY: 'U(IN)', color: '#2563eb', enabled: true },
        { id: 's2', plotIndex: 1, exprX: 't', exprY: 'U(OUT)', color: '#dc2626', enabled: true },
        { id: 's3', plotIndex: 2, exprX: 't', exprY: 'I(R1)', color: '#059669', enabled: true },
      ],
    },
  },

  // 4. Однофазный мостовой выпрямитель с емкостным сглаживанием
  {
    id: 'rectifier-bridge',
    name: 'Однофазный мостовой выпрямитель с C-фильтром',
    category: 'Силовые вентильные преобразователи',
    description: 'Двухполупериодный диодный выпрямитель переменного тока U = 220 В, 50 Гц со сглаживающим емкостным фильтром C1 = 220 мкФ и нагрузкой R1 = 20 Ом.',
    pageRef: 'Вентильные цепи',
    elements: [
      {
        id: 'u_grid',
        type: 'V_AC',
        name: 'U_GRID',
        x: 80,
        y: 200,
        rotation: 0,
        value: 220,
        valueStr: '220 В',
        unit: 'В',
        secondaryValue: 50,
        secondaryStr: '50 Гц',
      },
      {
        id: 'port_in',
        type: 'PORT',
        name: 'PORT_IN',
        portName: 'IN',
        x: 80,
        y: 120,
        rotation: 0,
        value: 0,
        valueStr: '',
        unit: '',
      },
      {
        id: 'vd1',
        type: 'DIODE',
        name: 'VD1',
        x: 220,
        y: 120,
        rotation: 0,
        value: 0,
        valueStr: 'Диод',
        unit: '',
      },
      {
        id: 'vd2',
        type: 'DIODE',
        name: 'VD2',
        x: 220,
        y: 220,
        rotation: 0,
        value: 0,
        valueStr: 'Диод',
        unit: '',
      },
      {
        id: 'c_filter',
        type: 'C',
        name: 'C1',
        x: 360,
        y: 180,
        rotation: 90,
        value: 220e-6,
        valueStr: '220 мкФ',
        unit: 'Ф',
      },
      {
        id: 'r_load',
        type: 'R',
        name: 'R_LOAD',
        x: 480,
        y: 180,
        rotation: 90,
        value: 20,
        valueStr: '20 Ом',
        unit: 'Ом',
      },
      {
        id: 'port_out',
        type: 'PORT',
        name: 'PORT_OUT',
        portName: 'OUT',
        x: 560,
        y: 120,
        rotation: 0,
        value: 0,
        valueStr: '',
        unit: '',
      },
      {
        id: 'gnd1',
        type: 'GND',
        name: 'GND1',
        x: 80,
        y: 280,
        rotation: 0,
        value: 0,
        valueStr: '',
        unit: '',
      },
      {
        id: 'gnd2',
        type: 'GND',
        name: 'GND2',
        x: 360,
        y: 280,
        rotation: 0,
        value: 0,
        valueStr: '',
        unit: '',
      },
      {
        id: 'gnd3',
        type: 'GND',
        name: 'GND3',
        x: 480,
        y: 280,
        rotation: 0,
        value: 0,
        valueStr: '',
        unit: '',
      },
    ],
    wires: [
      { id: 'w1', fromCompId: 'u_grid', fromPinId: '1', toCompId: 'port_in', toPinId: '1' },
      { id: 'w2', fromCompId: 'port_in', fromPinId: '1', toCompId: 'vd1', toPinId: '1' },
      { id: 'w3', fromCompId: 'vd1', fromPinId: '2', toCompId: 'c_filter', toPinId: '1' },
      { id: 'w4', fromCompId: 'c_filter', fromPinId: '1', toCompId: 'r_load', toPinId: '1' },
      { id: 'w5', fromCompId: 'r_load', fromPinId: '1', toCompId: 'port_out', toPinId: '1' },
      { id: 'w6', fromCompId: 'u_grid', fromPinId: '2', toCompId: 'gnd1', toPinId: '1' },
      { id: 'w7', fromCompId: 'c_filter', fromPinId: '2', toCompId: 'gnd2', toPinId: '1' },
      { id: 'w8', fromCompId: 'r_load', fromPinId: '2', toCompId: 'gnd3', toPinId: '1' },
    ],
    transient: {
      tMax: 0.04,
      tMaxStr: '40m',
      step: 5e-5,
      stepStr: '50u',
      eps: 0.001,
      signals: [
        { id: 's1', plotIndex: 1, exprX: 't', exprY: 'U(IN)', color: '#2563eb', enabled: true },
        { id: 's2', plotIndex: 1, exprX: 't', exprY: 'U(OUT)', color: '#dc2626', enabled: true },
        { id: 's3', plotIndex: 2, exprX: 't', exprY: 'I(R_LOAD)', color: '#059669', enabled: true },
        { id: 's4', plotIndex: 2, exprX: 't', exprY: 'I(VD1)', color: '#d97706', enabled: true },
      ],
    },
  },

  // 5. RLC колебательный контур (Переходный процесс)
  {
    id: 'rlc-oscillatory',
    name: 'RLC колебательный контур (Переходный процесс)',
    category: 'Переходные процессы',
    description: 'Последовательный колебательный RLC-контур при скачке напряжения 10 В. R = 5 Ом, L = 10 мГн, C = 10 мкФ. Затухающие колебания с частотой f_0 ~ 503 Гц.',
    pageRef: 'Теория цепей',
    elements: [
      {
        id: 'u_step',
        type: 'V_DC',
        name: 'U1',
        x: 80,
        y: 200,
        rotation: 0,
        value: 10,
        valueStr: '10 В',
        unit: 'В',
      },
      {
        id: 'port_in',
        type: 'PORT',
        name: 'PORT_IN',
        portName: 'IN',
        x: 80,
        y: 120,
        rotation: 0,
        value: 0,
        valueStr: '',
        unit: '',
      },
      {
        id: 'r1',
        type: 'R',
        name: 'R1',
        x: 200,
        y: 120,
        rotation: 0,
        value: 5,
        valueStr: '5 Ом',
        unit: 'Ом',
      },
      {
        id: 'l1',
        type: 'L',
        name: 'L1',
        x: 320,
        y: 120,
        rotation: 0,
        value: 0.01,
        valueStr: '10 мГн',
        unit: 'Гн',
      },
      {
        id: 'c1',
        type: 'C',
        name: 'C1',
        x: 440,
        y: 200,
        rotation: 90,
        value: 10e-6,
        valueStr: '10 мкФ',
        unit: 'Ф',
      },
      {
        id: 'port_out',
        type: 'PORT',
        name: 'PORT_OUT',
        portName: 'OUT',
        x: 520,
        y: 120,
        rotation: 0,
        value: 0,
        valueStr: '',
        unit: '',
      },
      {
        id: 'gnd1',
        type: 'GND',
        name: 'GND1',
        x: 80,
        y: 280,
        rotation: 0,
        value: 0,
        valueStr: '',
        unit: '',
      },
      {
        id: 'gnd2',
        type: 'GND',
        name: 'GND2',
        x: 440,
        y: 280,
        rotation: 0,
        value: 0,
        valueStr: '',
        unit: '',
      },
    ],
    wires: [
      { id: 'w1', fromCompId: 'u_step', fromPinId: '1', toCompId: 'port_in', toPinId: '1' },
      { id: 'w2', fromCompId: 'port_in', fromPinId: '1', toCompId: 'r1', toPinId: '1' },
      { id: 'w3', fromCompId: 'r1', fromPinId: '2', toCompId: 'l1', toPinId: '1' },
      { id: 'w4', fromCompId: 'l1', fromPinId: '2', toCompId: 'c1', toPinId: '1' },
      { id: 'w5', fromCompId: 'c1', fromPinId: '1', toCompId: 'port_out', toPinId: '1' },
      { id: 'w6', fromCompId: 'u_step', fromPinId: '2', toCompId: 'gnd1', toPinId: '1' },
      { id: 'w7', fromCompId: 'c1', fromPinId: '2', toCompId: 'gnd2', toPinId: '1' },
    ],
    transient: {
      tMax: 0.02,
      tMaxStr: '20m',
      step: 2e-5,
      stepStr: '20u',
      eps: 0.001,
      signals: [
        { id: 's1', plotIndex: 1, exprX: 't', exprY: 'U(IN)', color: '#2563eb', enabled: true },
        { id: 's2', plotIndex: 1, exprX: 't', exprY: 'U(OUT)', color: '#dc2626', enabled: true },
        { id: 's3', plotIndex: 2, exprX: 't', exprY: 'I(L1)', color: '#059669', enabled: true },
      ],
    },
  },
];
